### ISSUE TITLE
Print savestate operations to debug output

### ISSUE THREAD

**Issue by vadosnaprimer** [clementgallet/libTAS#100]
Sometimes I noticed that I needed feedback about state saves or loads, and OSD wasn't enough. I think printing this to console optionally might help in a few cases, for example when OSD disabled/bugged, or when the OSD message has already disappeared, and I need to check whether it was even there.

**Comment by clementgallet** [comment]
I added a debug message when saving or loading a state, also showing the savestate size and how long it took (8c80b0cf48f219946b62fb30fd6e70c8e0aef1a4). There are two new debug categories (Warning and Info), the above message belongs to the Info et Savestate debug categories.

Incidentally, this update clearly shows that there's a bug when both "Savestates in RAM" and "Incremental savestates" are set, because all savestates have the full size when they should be much smaller.

**Comment by vadosnaprimer** [comment]
Sorry for not testing this an older commits, but now when I have incremental and ram savestates enabled, loading a state I just saved, or loading the same state twice in a row, crashes mame.  Disabling either of those options fixes the crash.

**Comment by clementgallet** [comment]
Fixed in 73eadb7b3c4c4a830467f6456a9193b8ca2a4a9f

**Comment by vadosnaprimer** [comment]
Ugh, now it freezes upon last state reload when either of those savestates options is disabled, and crashes when I disable both, but works if both are on.

**Comment by clementgallet** [comment]
I'm very sorry about that, I checked everything this time (fixed in 2fd2f1823743c465c8f7099a578058ac07df4e0d).

**Comment by vadosnaprimer** [comment]
If I have ram states on and incremental states off, loading the satate I just saved still freezes it. Other ways seem to work.

**Comment by clementgallet** [comment]
I'm not getting any problem. What game/software are you using ? Could you test on the first frame of dosbox to see if it is game-related ?

**Comment by vadosnaprimer** [comment]
I do all my tests with MAME. I never tried dosbox in libtas, if it works I guess there is some difference between them. BTW I'm not doing this on the first frame. If you don't have MAME nearby anymore, just tell me, and I'll try dosbox. I just think it simply doesn't have the same problem.

**Comment by vadosnaprimer** [comment]
I can't even launch it with gdb attached:

```
Reading symbols from /usr/games/mame...Attempt 1: Couldn't connect to socket.
(no debugging symbols found)...done.
Signal        Stop	Print	Pass to program	Description
SIGUSR1       No	No	Yes		User defined signal 1
Signal        Stop	Print	Pass to program	Description
SIGUSR2       No	No	Yes		User defined signal 2
Signal        Stop	Print	Pass to program	Description
SIGPWR        No	No	Yes		Power fail/restart
Signal        Stop	Print	Pass to program	Description
SIGXCPU       No	No	Yes		CPU time limit exceeded
Signal        Stop	Print	Pass to program	Description
SIG35         No	No	Yes		Real-time event 35
Signal        Stop	Print	Pass to program	Description
SIG36         No	No	Yes		Real-time event 36
Starting program: /usr/games/mame btoads
Attempt 2: Couldn't connect to socket.
Attempt 3: Couldn't connect to socket.
Attempt 4: Couldn't connect to socket.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Attempt 5: Couldn't connect to socket.
Attempt 6: Couldn't connect to socket.
Attempt 7: Couldn't connect to socket.
Attempt 8: Couldn't connect to socket.
Attempt 9: Couldn't connect to socket.
Attempt 10: Couldn't connect to socket.
Got unknown message!!!
```

**Comment by clementgallet** [comment]
Found the bug (e7b5430a842c435ceaba80406c20fc6436f9defe). Base savestate was being asked to real an uninitialized amount of memory if incremental was off. Stangely, it only occured on Ubuntu 18.04.

It looks like you computer is so slow that it doesn't have time to launch the game before timeout. You can increase the timeout in `initSocketProgram()` (https://github.com/clementgallet/libTAS/blob/master/src/shared/sockethelpers.cpp#L38).

If you are using a VM, you can try increasing the allocated performances of the VM (what will mostly matter for libTAS is the number of processors and enough RAM).

**Comment by vadosnaprimer** [comment]
Woah nice! This is crazy that it's limited to a single ubuntu release! I'll test soon.

**Comment by vadosnaprimer** [comment]
Everything finally works, thanks for bearing with me!
