### ISSUE TITLE
[Wine] Cannot regain focus on window once out

### ISSUE THREAD

**Issue by InfamousKnight** [clementgallet/libTAS#262]
So testing midnight club 2 pc demo(funny how out of all wine games, this one I had the most success with, and its most desirable for me), if you go out of focus(like switching playback to recording to fix a mistake somewhere), the window will be stuck and can longer gain focus again. If recording and you lose focus of the window(like reading a manual or whatever) it will not capture any inputs(best tested unpaused).

Any ideas on how to fix this?

**Comment by InfamousKnight** [comment]
To confirm it is a wine only issue, I tested some known working linux applications, and I can regain focus fine on those still. For any known working wine game, it doesn't allow me to. I tested Sonic the hedgehog 3d(made with Eduke engine), and a startup message appears, then the game window with OSD, and it won't let me gain focus on it.

**Comment by clementgallet** [comment]
I'm not getting this issue anymore. Was it fixed with 83b749d847ce5b1d7a78a3fa50989237167324bd ?

**Comment by InfamousKnight** [comment]
Im still getting it.. on arch. Ill test out ubuntu 18.04 tomorrow.

**Comment by InfamousKnight** [comment]
Using 18.04, testing midnight club 2 demo, on wine stable release, now the game just crashes in I regain focus.

I can't seem to copy the backtrace either..
